### PR TITLE
Add yarn.lock

### PR DESCRIPTION
**Pull request by winksaville**
Using [yarn](https://www.npmjs.com/package/yarn) has some
advantages such as consistent versions of npm modules.

### CODE REVIEW

**Comment by dcodeIO** [comment]
I'd like to postpone this, and then probably combine it with npm-shrinkwrap, until a final set of dependencies is known.

**Comment by winksaville** [comment]
That's fine, but just so you know that using yarn.lock is in no way
"permanent" and the module versions can and should be `upgraded`
frequently. What it does mean is that everyone will be on the same version
of the modules which can be important when trying to reproducing bugs.

**Comment by dcodeIO** [comment]
Now includes npm5's `package-lock.json`. Probably something yarn will support as well in the future if no yarn.lock can be found, I assume.

**Comment by dcodeIO** [comment]
Tracking issue: https://github.com/yarnpkg/yarn/issues/3614

**Comment by dcodeIO** [comment]
From the comments of the tracking issue above it seems that developers have to decide for one of the lock files anyway, ignoring the other one, because it's just too hard to sync them. Hence, betting on eventual `package-lock.json` support in yarn seems like the best we can do.

Closing this issue for now. Feel free to reopen if necessary.

**Pull request closed without merging**
