### PR TITLE
fix build script

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Hmm, didn't it work with the initial [arguments](https://github.com/mishoo/UglifyJS2#command-line-options)?

**Comment by MaxGraey** [comment]
Didn't work because 'dist/assemblyscript.min.js' was not found.

**Comment by dcodeIO** [comment]
Ah, I see. I was considering `out/` as the temporary location for building the TS sources, and `dist/` as the final destination of the final files. Is it correct to assume that just the `dist/` folder was missing when you tried? If so, we should just add the folder to source control through a placeholder inside.

**Comment by MaxGraey** [comment]
yse, I think problem with initially lacking of ```dist``` directory. Actully I more prefer Webpack and Rollup for fine tuning and speed of build process

**Comment by dcodeIO** [comment]
I tried webpack first, but I figured that it didn't provide fine grained control over the build process, so I ended up with a two-step build process - first building the TS files the usual way to CommonJS-style files, then bundling it up with the prebuilt binaryen and typescript sources, and browserify seemed like a better match for this because it's just a simple one-shot command line.

**Pull request closed without merging**
