### PR TITLE
add class fixture

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
I though about adding class tests as well. These shouldn't include malloc probably because it'll bloat the test case.

Btw., you can generate the respective fixture and check it by hand before checking in a test by running `npm test -- --create`.

**Comment by MaxGraey** [comment]
So maybe create two separete directory? One for ordinal fixtures, another one for fixtures require std lib

**Comment by dcodeIO** [comment]
The `fixtures/` folder is meant to contain only tests that check the wast representation. Hence, it shouldn't be a problem to compile with `malloc: false` there as the generated code is the same. It might be necessary though to import `malloc` etc. in this case so compilation doesn't throw when using classes, as in this case.

Actual functional tests would go to another directory, just as you assumed.

**Comment by MaxGraey** [comment]
By the way. This code:

```ts
class Foo {
    constructor() {}
}

let a: Foo = new Foo();
```

Generate wast and wasm. But it not valid (if you turn validate). I got this while validation stage:

```bash
index.js:554 Uncaught Assertion failed: mappedFunctions.count(name), at: src/wasm/wasm-binary.cpp,342,getFunctionIndex at Error
    at wa (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:8:170)
    at ___assert_fail (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:561:379)
    at Zm (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:576:10045)
    at Nl (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:573:135837)
    at zk (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:573:84333)
    at Vx (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:575:90143)
    at Jj (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:573:47868)
    at Up (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:576:91700)
    at zk (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:573:84468)
    at Vx (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:575:90143)
    at Jj (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:573:47868)
    at qh (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:574:80002)
    at zk (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:573:84223)
    at Vx (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:575:90143)
    at Jj (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:573:47868)
    at nM (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:578:82432)
    at dd (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:580:81989)
    at Array.fr (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:576:120913)
    at Object.Zpa [as dynCall_vi] (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:582:111391)
    at invoke_vi (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:553:492)
    at Object.bs [as _BinaryenModuleWrite] (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:576:140142)
    at Ua.a.Module.emitBinary (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:651:358)
```

**Comment by dcodeIO** [comment]
Seems that the constructor doesn't become compiled. Going to look into it.

Regarding the tests, there is now an initial [README outlining the test process](https://github.com/dcodeIO/AssemblyScript/blob/master/tests/README.md).

**Comment by MaxGraey** [comment]
Hmm. This code cause very close to above failure:

```ts
export function fib(n: int32): int32 {
    if (n <= 1) return 1;
    return fib(n - 1) + fib(n - 2);
}
```

```
functionsMap.find(curr->name) == functionsMap.end(), at: src/wasm/wasm.cpp,642,addFunction at Error
    at wa (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:8:170)
    at ___assert_fail (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:561:379)
    at Array.Aq (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:576:107015)
    at Object.Lma [as dynCall_vii] (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:582:103690)
    at invoke_vii (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:554:110)
    at Object.Bh [as _BinaryenAddFunction] (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:574:92951)
    at https://rawgit.com/dcodeIO/binaryen.js/master/index.js:649:65
    at G (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:23:243)
    at Ua.a.Module.addFunction (https://rawgit.com/dcodeIO/binaryen.js/master/index.js:649:43)
    at t.compileFunction (https://rawgit.com/dcodeIO/AssemblyScript/master/dist/assemblyscript.min.js:7:60218)
    at t.compile (https://rawgit.com/dcodeIO/AssemblyScript/master/dist/assemblyscript.min.js:7:57433)
    at Function.t.compileProgram (https://rawgit.com/dcodeIO/AssemblyScript/master/dist/assemblyscript.min.js:7:50302)
    at Function.t.compileString (https://rawgit.com/dcodeIO/AssemblyScript/master/dist/assemblyscript.min.js:7:49506)
...
```

But I use current bundle from 'dist' folder.

**Comment by dcodeIO** [comment]
Might be that the dist files haven't been updated yet.

**Comment by MaxGraey** [comment]
But both ref to binaryen.js

**Comment by dcodeIO** [comment]
Yeah, that usually happens if something is done entirely wrong on the compiler side of things.

**Pull request closed without merging**
