### PR TITLE
Short explicetly cast to double by unary '+'

### PR DESCRIPTION
**Pull request by MaxGraey**
Just for compatibles with typescript.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Doesn't this catch all unary expressions?

**Comment by MaxGraey** [comment]
Yep, I will fix now

**Comment by MaxGraey** [comment]
I hope now is correct.

**Comment by dcodeIO** [comment]
Currently looking at it. I am not exactly sure that this is what we want. I know that's how it works in JS/TS, but well, we have proper casts. Doesn't that contradict their purpose?

**Comment by MaxGraey** [comment]
I thought about it. It's depending on how exactly you want follow typescript spec and if you worry about easily code portability from ts -> AssemblyScript in my opinion it should implement or polyfilled.

**Comment by MaxGraey** [comment]
By the way ```op.(i32 | i64).eqz``` should implement and for ```EqualsEqualsToken``` in ```BinaryExpression``` for better performance

**Comment by dcodeIO** [comment]
We can do that, but with the binaryen integration in place, we already have access to its optimizer.

**Comment by dcodeIO** [comment]
I'm still writing this in quite a hurry, so keep letting me know if you spot more issues :)

**Pull request closed without merging**
