### PR TITLE
Add sized types

### PR DESCRIPTION
**Pull request by winksaville**
TODO: @dcodeIO, if you think this is acceptable I can update the compiler.

### CODE REVIEW

**Comment by dcodeIO** [comment]
I'd suggest to think about adding additional type aliases later - once the compiler actually produces something useful :)

**Comment by winksaville** [comment]
SG, at least you didn't reject it outright. Personally I tend to use the
sized types more than "regular" types like int/uint/long/ulong/... and I
think it fits well into the wasm eco-system. Of course YMMV.

**Comment by dcodeIO** [comment]
It should now be possible to add this yourself by defining the respective type aliases. These are followed to the built-in types now.

**Comment by winksaville** [comment]
That's great but don't you think there should be an official set of these?

**Comment by dcodeIO** [comment]
I believe we should avoid redundancy where possible, and especially where custom functionality is as easily added as in this case. Less code to maintain = less issues. Less redundancy = less questions to ask.

Personally, I'm fine with the c-like types for the reason that I can type them faster because I don't have to switch between letters and numbers constantly.

**Comment by winksaville** [comment]
One thing, are you going to guarantee that the sizes of your current types
won't change as things evolve, what about 128 bit ints or floats, using
size encoded solves that problem. Anyway not a big deal, this is just my
opinion.

**Comment by dcodeIO** [comment]
> One thing, are you going to guarantee that the sizes of your current types
won't change as things evolve

Yeah, that's the plan. If anything else becomes necessary in the future, it's not a big deal to add it. Just want to avoid having redundant type names for now (doesn't mean forever - I see your point there).

**Comment by dcodeIO** [comment]
FYI: https://github.com/dcodeIO/AssemblyScript/blob/master/assembly.d.ts#L47

**Comment by winksaville** [comment]
Nice!

**Pull request closed without merging**
