### PR TITLE
Add comparisions

### PR DESCRIPTION
**Pull request by MaxGraey**
Example:

```ts
export function isEqual(a: float, b: float): bool {
    return (a == b) as bool;
}

export function isGreater(a: int, b: int): bool {
    return (a > b) as bool;
}
```

Now with explicitly casting. Need implement general implicitly casting to bool for any type.

### CODE REVIEW

**Comment by dcodeIO** [comment]
That's where the `bool` thing comes into play again. It's necessary to decide whether bools are entirely a logical type or an arithmetic (int) type.

**Comment by dcodeIO** [comment]
This now heads towards the arithmetic route, as it is on the binary level. Imho we should try to stay close to wasm where possible, as that's what we want to produce ultimately.

**Comment by MaxGraey** [comment]
I think it would be logical with implicitly forward/backward casts because logical ops should always return bool

```ts
var a: bool = c > 0 && b < 0
```

**Comment by dcodeIO** [comment]
Your example would currently evaluate to `1 && 1` for example (if c > 0 and b < 0) as the wasm operations return zero or one.

**Comment by MaxGraey** [comment]
In most languages ```bool``` is integral type and represent as integer. But we need somehow differentiate integer from booleans in rumtime or this no make sense? And how about ternary operator?

**Comment by MaxGraey** [comment]
Another example:

```ts
let b: bool = 123;
let r: int = 123 - b;
```
Without casting we get **0** but sgoud **122**. Or we should disable implicitly casting to bool, but this has a lot of side effects

**Comment by MaxGraey** [comment]
Hmm, by the way typescript can't implicitly cast from boolean to number:
```ts
var t: boolean = true;
var res: number = 126.0 - t;
```

Only with explicitly:
```ts
var res: number = 126.0 - +t;
```

**Pull request closed without merging**
