### PR TITLE
Add simple compilation time statistics

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Looks like one of your previous PRs sneaked in, adding another layer of hex num. Is that correct?

**Comment by MaxGraey** [comment]
It's ok. I just add time profiling in this PR

**Comment by MaxGraey** [comment]
if you about "make allowing parsing hex num literals and add yarn lock". Don't worry,  it fixed after couple of merges from remote main branch. You can [check](https://github.com/dcodeIO/AssemblyScript/pull/5/files)

**Comment by dcodeIO** [comment]
Merged this manually, thanks!

**Pull request closed without merging**
