### PR TITLE
add runtime info (version)

### PR DESCRIPTION
**Pull request by MaxGraey**
New Compiler methods about compiler:
- Compiler.version property (read from package.json)

### CODE REVIEW

**Comment by dcodeIO** [comment]
Not sure about the compatibility table (imho it's too early to add something like this), but we could of course add the version to `index.ts`.

**Comment by MaxGraey** [comment]
I think use compatibility for compare between different compilers in playground

**Comment by dcodeIO** [comment]
I'd suggest to add this to the playground instead for now.

**Comment by MaxGraey** [comment]
Ok. I leave only version property

**Comment by dcodeIO** [comment]
Added this to index.ts. There is now `assemblyscript.pkg` holding the contents of package.json and `assemblyscript.version` referencing the version for convenience.

**Comment by MaxGraey** [comment]
Hmm, I don't understand what you mean. I just simply close this PR and you are free to implement this if you don't mind

**Comment by dcodeIO** [comment]
For reference:
- https://github.com/dcodeIO/AssemblyScript/blob/master/src/index.ts#L20
- https://github.com/dcodeIO/AssemblyScript/blob/master/src/index.ts#L25

**Comment by MaxGraey** [comment]
ok, thanks!

**Pull request closed without merging**
