### PR TITLE
Implements array's push method

### PR DESCRIPTION
**Pull request by MaxGraey**
Need review and some discussions.

1. Test generate strange symbol name ``` $std/array.ts/Array<double>#push ``` instead ``` $std/array.ts/Array<int>#push```.
2. What on you opinion ideal memory grow rate **2** (C#, C++/std), **1.5** (Java) or mixed like in FBVector?

### CODE REVIEW

**Comment by dcodeIO** [comment]
Question here is: Do we really want to support .push? I am feeling more comfortable with a readonly length property.

**Comment by MaxGraey** [comment]
The most languages support dynamic length in his Array-like objects. A lot codebase of typescript and js build around push/pop so in my opinion it's should be done at least for compatibility and ease migration.

**Comment by dcodeIO** [comment]
If that's your intend behind supporting .push, well, note that you'll never be able to compile standard TypeScript/JavaScript to WebAssembly without (at least largely) reimplementing a JS VM/JIT anyway. [See also](https://github.com/dcodeIO/AssemblyScript#what-to-expect).

**Comment by MaxGraey** [comment]
@dcodeIO I understand current limitations. But I still can't understand why you implement slice, reverse, indexOf, lastIndexOf, startsWith and widthWith but don't make more important method **push**?

**Comment by dcodeIO** [comment]
> I still can't understand why you implement slice, reverse, indexOf, lastIndexOf, startsWith and widthWith but don't make more important method push

I implemented a couple of methods as a starting point, to get an idea of it. That didn't involve any judgement on the importance of these functions.

To me, .push is only useful when working with variable-sized arrays. If possible, I try to resort to an indexed assignment following on a fixed-size instantiation because it is more efficient, also in JavaScript itself. Also note that in WebAssembly, an assignment compiles to just a store opcode.

**Comment by MaxGraey** [comment]
So reason is to avoid runtime checking bounds of array while access to indexed element? What about include **safe** compile option for turn-on/turn-off this checking [like done this in speedy.js](https://github.com/MichaReiser/speedy.js/blob/master/packages/runtime/lib/array.h#L117)?

**Comment by dcodeIO** [comment]
> So reason is to avoid runtime checking bounds of array while access to indexed element?

That's another issue we'll have to think about. I might have misunderstood your PR a bit as it didn't seem to implement `length` as a mutable property a user can assign any value to. The commit above should make stuff like this easier.

**Comment by MaxGraey** [comment]
Thanks! Little bit later I adopt this to my PR.

**Comment by dcodeIO** [comment]
Seems there are a few other things to update. Currently looking into it, will let you know.

**Comment by dcodeIO** [comment]
While implementing a `grow(newCapacity)` method, I realized that automatic resizing exhibits unsafe behavior in that it frees the old reference and allocates a new one, which is relevant when using `push`. For example:

```ts
var arr: int[] = ...;
arr.push(5);
```

When `.push` has to grow memory, the reference in `arr` (and any other references to the same array in other contexts) are free'd, which cannot be done transparently to the user.

We could work around this issue by splitting up the array struct into a descriptor and a data region referenced within the descriptor, with the data region being replaceable. Though, this will result in an additional load operation every time data is accessed.

**Comment by MaxGraey** [comment]
I will create new PR because now there are a lot of unresolved conflicts

**Comment by RangerMauve** [comment]
What about backing variable length arrays with a linked list? You lose a bunch of performance, but it enables this use case while not losing any performance with static-length arrays.

**Comment by dcodeIO** [comment]
If it is named array, it should probably be one. We could still add a `List` implementation to the standard library, though.

**Comment by RangerMauve** [comment]
My only worry about adding a List type is that regular TypeScript won't be able to use it. Though I guess it wouldn't be too hard to overcome.

If the List is explicitly imported, it'd be easier to create the same implementation in TypeScript.

**Comment by RangerMauve** [comment]
If anything, implementing a LinkedList in AssemblyScript is pretty easy to do.

**Comment by dcodeIO** [comment]
Well, how AssemblyScript is implemented currently, its type system isn't portable to JavaScript anyway. For example, casting any derived type to another does nothing when compiled to JavaScript. In JavaScript, any numeric type is just a `Number`.

**Pull request closed without merging**
